{{- if and ( .Capabilities.APIVersions.Has "cert-manager.io/v1" ) .Values.certificates.enabled .Values.certificates.cluster.enabled }}
# Self Signed Kong Cluster Certificate
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kong.fullname" . }}-cluster-cert
  namespace:  {{ template "kong.namespace" . }}
  labels:
    {{- include "kong.metaLabels" . | nindent 4 }}
spec:
  secretName: {{ include "kong.fullname" . }}-cluster-cert
  commonName: kong_cluster
  dnsNames:
  - "kong_cluster"
  issuerRef:
    name: {{ template "kong.certificate.issuer" . }}
    kind: ClusterIssuer
  renewBefore: 360h
  duration: 2160h
  isCA: false
{{- end }}